import React from 'react';
import { BrandingConfig } from '../types';
import { ShieldCheck, FileText, Lock, Scale, AlertCircle, ArrowLeft, ArrowRight, HelpCircle, Mail, Phone, MapPin } from 'lucide-react';

interface TermsPageProps {
  branding: BrandingConfig;
  onOpenDemoModal: () => void;
  onNavigateHome: () => void;
  onNavigatePrivacy: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({
  branding,
  onOpenDemoModal,
  onNavigateHome,
  onNavigatePrivacy,
}) => {
  return (
    <div className="bg-[#FAF9F6] text-slate-900 min-h-screen text-left">
      
      {/* Header Banner */}
      <section className="bg-slate-900 text-white py-14 lg:py-18 border-b border-slate-800">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-4">
            <button
              onClick={onNavigateHome}
              className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-400 hover:text-amber-300 transition-colors cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Home</span>
            </button>

            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-amber-500/20 border border-amber-400/30 text-amber-300 text-xs font-semibold">
              <Scale className="w-3.5 h-3.5" />
              <span>Legal Agreement & User Terms</span>
            </div>

            <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-white font-heading">
              Terms & Conditions
            </h1>

            <p className="text-slate-300 text-sm sm:text-base leading-relaxed font-body max-w-3xl font-medium">
              These Terms and Conditions govern the access and use of the {branding.brandName} platform, live spoken English classrooms, debate studios, 1-on-1 mentorship programs, and allied services.
            </p>

            <div className="pt-2 flex flex-wrap items-center gap-4 text-xs text-slate-400">
              <span>Last Updated: September 20, 2026</span>
              <span>•</span>
              <span>Governed by Information Technology Act, 2000 (India)</span>
            </div>
          </div>
        </div>
      </section>

      {/* Main Document Body */}
      <section className="py-12 lg:py-16 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-3xl p-6 sm:p-10 lg:p-14 border border-slate-200 shadow-sm space-y-10 font-body text-slate-700 leading-relaxed text-sm sm:text-base">
          
          {/* Section 1 */}
          <div className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">1</span>
              <span>Introduction & Acceptance of Terms</span>
            </h2>
            <p>
              <strong>1.1</strong> {branding.brandName} (hereinafter referred to as <strong>“{branding.brandName}”</strong>, <strong>“We”</strong>, <strong>“Us”</strong>, or the <strong>“Company”</strong>) is an Indian EdTech platform offering live online communication, extempore speech coaching, phonetics, storytelling, and Oxford debate education for children (Grades UKG to 10).
            </p>
            <p>
              <strong>1.2</strong> These Terms and Conditions (<strong>“Terms”</strong> or <strong>“T&C”</strong>) govern your access to and use of our website, web application, mobile applications, interactive speaking studios, courseware, and associated digital platforms (collectively, the <strong>“Platform”</strong>).
            </p>
            <p>
              <strong>1.3</strong> These Terms constitute an electronic record within the meaning of the <strong>Information Technology Act, 2000</strong> and rules made thereunder. This electronic record is generated by a computer system and does not require physical or digital signatures.
            </p>
            <p>
              <strong>1.4</strong> By visiting, registering, booking a demo, or enrolling your ward in any program on the Platform, you acknowledge that you have read, understood, and voluntarily agreed to be legally bound by these Terms and our allied <button onClick={onNavigatePrivacy} className="text-amber-700 font-bold underline cursor-pointer">Privacy Policy</button>. If you do not agree with any provision herein, you must immediately cease accessing the Platform.
            </p>
          </div>

          {/* Section 2 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">2</span>
              <span>Mandatory Parental Consent for Minors (Under Age 18)</span>
            </h2>
            <p>
              <strong>2.1</strong> The Services provided by {branding.brandName} are designed for school students (hereinafter referred to as the <strong>“Student”</strong> or <strong>“Child”</strong>). Since Students are minors below 18 years of age, registration, subscription, payment, and consent must be strictly executed by the parent or legal guardian (hereinafter referred to as the <strong>“Parent”</strong> or <strong>“User”</strong>).
            </p>
            <p>
              <strong>2.2</strong> By enrolling a Student, the Parent represents and covenants that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The Parent is of legal age (18 years or older) and possesses full legal competence and authority to enter into binding agreements on behalf of the Child.</li>
              <li>The Parent grants voluntary and unconditional consent for the Student to attend live speaking classes, extempore drills, group discussions, and diagnostic speech assessments.</li>
              <li>The Parent shall maintain reasonable parental vigilance and supervision over the Child's participation and internet connectivity.</li>
              <li>The Parent assumes full and complete liability for any acts, submissions, or conduct of the Student during live sessions.</li>
            </ul>
          </div>

          {/* Section 3 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">3</span>
              <span>Nature of Services & Classroom Formats</span>
            </h2>
            <p>
              <strong>3.1</strong> {branding.brandName} delivers live, interactive pedagogical training in spoken English fluency, dramatic voice modulation, impromptu public speaking, and structured debate. The Platform operates as a virtual speech laboratory and does not operate physical brick-and-mortar coaching centers.
            </p>
            <p>
              <strong>3.2</strong> Services are offered in two distinct modalities:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Interactive Small-Group Batches:</strong> Intimate cohorts where students practice speaking drills with peers, receive real-time feedback, and practice debates with guaranteed active microphone time.</li>
              <li><strong>1-on-1 Private Mentorship Classes:</strong> Dedicated 1-on-1 sessions where 100% of the class time is personalized to the individual student with custom scheduling and bespoke pace.</li>
            </ul>
            <p>
              <strong>3.3</strong> The Services are intended to supplement, reinforce, and enhance conversational confidence and do not replace mandatory statutory school curricula.
            </p>
          </div>

          {/* Section 4 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">4</span>
              <span>Explicit Consent for Session Recordings & Quality Audits</span>
            </h2>
            <p>
              <strong>4.1</strong> To ensure child safety, maintain pedagogical rigor, evaluate educator quality, and generate personalized parent speech diagnostic reports, {branding.brandName} records audio, video, chat, and screen interactions during live sessions.
            </p>
            <p>
              <strong>4.2</strong> The Parent hereby explicitly consents to the recording of the Student's audio, video, and spoken interactions during live sessions. Such recordings are securely processed in strict adherence to our Privacy Policy and applicable child protection frameworks (including POSH guidelines).
            </p>
            <p>
              <strong>4.3</strong> Users and Students are strictly prohibited from independently recording, screen-capturing, downloading, publishing, or sharing any portion of live sessions, mentor lectures, or peer videos on social media or external websites.
            </p>
          </div>

          {/* Section 5 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">5</span>
              <span>Intellectual Property Rights & Proprietary Pedagogy</span>
            </h2>
            <p>
              <strong>5.1</strong> All intellectual property associated with the Platform, including but not limited to the <strong>PEEI Debate Framework</strong>, 30-Second Extempore Prompts, Storytelling Labs, speech exercises, worksheets, lesson slides, audio benchmarks, logos, graphics, software code, and pedagogical frameworks, are the sole and exclusive intellectual property of {branding.brandName}.
            </p>
            <p>
              <strong>5.2</strong> Users are granted a limited, personal, non-exclusive, non-transferable, revocable license strictly to access the learning materials for personal, non-commercial education. You may not copy, reverse engineer, decompile, redistribute, license, publish, or commercially exploit any courseware without prior written authorization from the Company.
            </p>
          </div>

          {/* Section 6 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">6</span>
              <span>Enrollment, Fees & Payment Mechanisms</span>
            </h2>
            <p>
              <strong>6.1</strong> All fees for courses, small-batch subscriptions, and 1-on-1 packages are quoted in Indian Rupees (INR) and are payable in advance through authorized, secure third-party payment gateways (including Credit Cards, Debit Cards, Net Banking, UPI, and authorized EMI providers).
            </p>
            <p>
              <strong>6.2</strong> The Company does not directly capture, store, or process full credit card numbers or CVV codes on our servers; all transactions are encrypted and processed by RBI-authorized payment processors.
            </p>
            <p>
              <strong>6.3</strong> {branding.brandName} reserves the right to modify course pricing, fee tiers, or promotional concessions at its sole discretion, provided that active enrolled term plans shall remain unaffected until the term renewal.
            </p>
          </div>

          {/* Section 7 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">7</span>
              <span>Batch Allocation, Mentor Assignment & Scheduling</span>
            </h2>
            <p>
              <strong>7.1 Batch Placement:</strong> Following demo assessment and fee payment, {branding.brandName} allocates a suitable peer cohort based on the Student's grade tier, cognitive baseline, and convenient time slot. Batch allocation typically completes within 7 to 14 business days.
            </p>
            <p>
              <strong>7.2 Mentor Assignment:</strong> Mentors are allocated based on pedagogical specialization. While we maintain consistent mentorship, the Company reserves the right to reassign trainers due to scheduling constraints, health emergencies, or curriculum advancement.
            </p>
            <p>
              <strong>7.3 Batch Change Requests:</strong> Requests to change assigned batch timing or days must be submitted in writing via official support channels with at least 7 days advance notice and are subject to slot availability.
            </p>
          </div>

          {/* Section 8 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">8</span>
              <span>Batch Pause & Leave Policy</span>
            </h2>
            <p>
              <strong>8.1</strong> In case of school examinations, illness, or family travel, parents enrolled in multi-month term programs may apply for a temporary Batch Pause (up to 30 calendar days) by contacting support.
            </p>
            <p>
              <strong>8.2</strong> Classes missed without prior intimation shall be marked as completed, but students will retain access to session recordings and homework review materials.
            </p>
          </div>

          {/* Section 9 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">9</span>
              <span>Refund & Satisfaction Guarantee Policy</span>
            </h2>
            <p>
              <strong>9.1 Flagship 7-Day Guarantee:</strong> For eligible full 12-week term flagship programs, parents who attend their first 2 scheduled batch classes and are not satisfied with the mentorship quality may request a full refund within 7 calendar days of their batch start date.
            </p>
            <p>
              <strong>9.2 Non-Eligible Refund Scenarios:</strong> Refunds shall not be processed in scenarios including:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Student unexcused absenteeism or refusal to turn on camera/microphone during live drills.</li>
              <li>Personal schedule conflicts or relocation arising after the 7-day initial guarantee window.</li>
              <li>Monthly starter batches where classes have already been consumed.</li>
            </ul>
            <p>
              <strong>9.3 Processing Timeline:</strong> Approved refunds are credited back to the original source payment instrument within 7 to 10 working days, subject to standard bank processing.
            </p>
          </div>

          {/* Section 10 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">10</span>
              <span>Code of Conduct, Minor Safety & Zero-Tolerance Policy</span>
            </h2>
            <p>
              <strong>10.1 Safe Space Protocol:</strong> {branding.brandName} is dedicated to nurturing self-conscious children. Mocking, bullying, abusive language, discrimination, or disruptive behavior towards fellow students or coaches is strictly prohibited.
            </p>
            <p>
              <strong>10.2 Disciplinary Action:</strong> The Company reserves the immediate right to suspend or permanently expel any user or student who violates classroom decorum or engages in inappropriate conduct, without refund entitlement.
            </p>
          </div>

          {/* Section 11 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">11</span>
              <span>Limitation of Liability & Disclaimer of Warranties</span>
            </h2>
            <p>
              <strong>11.1</strong> The Services and content are provided on an <strong>“AS IS”</strong> and <strong>“AS AVAILABLE”</strong> basis without warranties of any kind, whether express or implied.
            </p>
            <p>
              <strong>11.2</strong> While our pedagogical drills consistently accelerate spoken English proficiency and confidence, {branding.brandName} does not guarantee specific individual outcomes such as school exam marks, competition trophies, or student council election victories.
            </p>
            <p>
              <strong>11.3</strong> In no event shall {branding.brandName}, its directors, officers, mentors, or employees be liable for any indirect, incidental, special, consequential, or punitive damages. The total aggregate liability of the Company shall be strictly limited to the actual amount paid by the User for the specific course in question.
            </p>
          </div>

          {/* Section 12 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">12</span>
              <span>Indemnification</span>
            </h2>
            <p>
              You agree to defend, indemnify, and hold harmless {branding.brandName}, its affiliates, directors, educators, and contractors from and against any claims, liabilities, damages, losses, costs, or expenses (including reasonable legal fees) arising from: (a) your or your ward's breach of these Terms; (b) misuse of the Platform; or (c) violation of applicable laws or third-party rights.
            </p>
          </div>

          {/* Section 13 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">13</span>
              <span>Governing Law, Jurisdiction & Dispute Resolution</span>
            </h2>
            <p>
              <strong>13.1 Governing Law:</strong> These Terms shall be governed by, interpreted, and construed in accordance with the substantive laws of the Republic of India.
            </p>
            <p>
              <strong>13.2 Arbitration:</strong> Any dispute, controversy, or claim arising out of or relating to these Terms shall be resolved amicably through mutual discussions. If unresolved within 30 days, the dispute shall be referred to and finally resolved by binding arbitration under the <strong>Arbitration and Conciliation Act, 1996</strong> (as amended) by a Sole Arbitrator appointed by {branding.brandName}. The seat and venue of arbitration shall be in India, and the language of proceedings shall be English.
            </p>
            <p>
              <strong>13.3 Jurisdiction:</strong> Subject to the arbitration clause above, courts situated in India shall possess exclusive jurisdiction over any matters arising hereunder.
            </p>
          </div>

          {/* Section 14 */}
          <div className="space-y-3 pt-6 border-t border-slate-100">
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 font-heading flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-xl bg-amber-100 text-amber-900 text-xs flex items-center justify-center font-bold">14</span>
              <span>Grievance Officer & Legal Contact</span>
            </h2>
            <p>
              In accordance with the <strong>Information Technology Act, 2000</strong> and rules made thereunder, questions, legal notices, or grievances regarding these Terms may be addressed to our designated officer:
            </p>
            
            <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-2 text-xs sm:text-sm">
              <p><strong>Designated Grievance & Compliance Officer:</strong> Legal & Compliance Department</p>
              <p><strong>Entity Name:</strong> {branding.brandName} EdTech Operations</p>
              <p><strong>Official Email:</strong> <a href={`mailto:${branding.contactEmail}`} className="text-amber-700 font-bold underline">{branding.contactEmail}</a></p>
              <p><strong>Support Phone:</strong> {branding.contactPhone}</p>
              <p><strong>Support WhatsApp:</strong> {branding.supportWhatsapp}</p>
            </div>
          </div>

        </div>

        {/* Bottom Navigation Buttons */}
        <div className="mt-10 flex flex-col sm:flex-row items-center justify-between gap-4">
          <button
            onClick={onNavigatePrivacy}
            className="text-xs sm:text-sm font-black text-amber-800 hover:text-amber-950 flex items-center gap-1.5 cursor-pointer font-heading"
          >
            <span>Read Privacy Policy & Minor Safety</span>
            <ArrowRight className="w-4 h-4" />
          </button>

          <button
            onClick={onOpenDemoModal}
            className="px-6 py-3.5 rounded-full bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-slate-950 font-black text-xs sm:text-sm font-heading flex items-center gap-2 cursor-pointer shadow-md hover:shadow-lg transition-all"
          >
            <span>Book a Free Demo Class</span>
            <ArrowRight className="w-4 h-4 text-slate-950" />
          </button>
        </div>
      </section>

    </div>
  );
};
